# Generated by Django 3.1.1 on 2020-09-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
