# Generated by Django 3.1.1 on 2020-09-15 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200915_2354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Readings',
            new_name='Reading',
        ),
    ]
