# Generated by Django 3.1.1 on 2020-09-16 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200916_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('reading', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.reading')),
                ('answer1', models.CharField(max_length=10)),
                ('answer2', models.CharField(max_length=10)),
                ('answer3', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='reading',
            name='risk',
            field=models.CharField(default='yes', max_length=10),
            preserve_default=False,
        ),
    ]
